<?php

/**
 * Mapa de labels humanos para cada campo (columna DB) por modulo auditable.
 * Los textos coinciden lo mas posible con los labels de los formularios edit
 * de cada modulo, para que la snapshot de un registro eliminado se vea
 * familiar al usuario.
 *
 * Keys = nombres EXACTOS de modulo guardados en activity_logs.module.
 * Cualquier campo sin entrada cae al humanizer (ucfirst + str_replace).
 */
return [
    'Vehículos' => [
        'sort_order'         => 'Orden',
        'plate'              => 'Placa',
        'headquarters'       => 'Sede',
        'entry_date'         => 'F. Ingreso',
        'termination_date'   => 'Fecha Cese',
        'class'              => 'Categoría',
        'brand'              => 'Marca',
        'year'               => 'Año Fabricación',
        'model'              => 'Modelo',
        'bodywork'           => 'Carrocería',
        'color'              => 'Color',
        'type'               => 'Modalidad',
        'affiliated_company' => 'Empresa Afiliada',
        'condition'          => 'Condición',
        'owner_id'           => 'Propietario',
        'driver_id'          => 'Conductor',
        'fuel'               => 'Combustible',
        'soat_date'          => 'Soat F.V',
        'certificate_date'   => 'Certificado Op.F.V',
        'technical_review'   => 'Revisión Técnica F.V',
        'detail'             => 'Detalle',
        'validity_status'    => 'Estado de vigencia',
        'status'             => 'Estado',
        'seats'              => 'Asientos',
        'passengers'         => 'Pasajeros',
    ],
    'Conductores' => [
        'name'                                 => 'Nombres',
        'document_number'                      => 'N° Documento',
        'document_expiration_date'             => 'Doc F.Vencimiento',
        'birthdate'                            => 'Fecha Nacimiento',
        'email'                                => 'Email',
        'district'                             => 'Distrito',
        'address'                              => 'Dirección',
        'phone'                                => 'Teléfono',
        'license'                              => 'Licencia',
        'class'                                => 'Clase',
        'category'                             => 'Categoría',
        'license_issue_date'                   => 'Licencia: Fecha Expedición',
        'license_revalidation_date'            => 'Licencia: Fecha Revalidación',
        'contract_start'                       => 'F.Inicio Contrato',
        'contract_end'                         => 'F.Fin Contrato',
        'condition'                            => 'Condición',
        'status'                               => 'Estado',
        'cartilla_informativa'                 => 'Cartilla Informativa: Fecha Expedición',
        'cartilla_informativa_expiration_date' => 'Cartilla Informativa: Fecha Vencimiento',
        'cartilla_informativa_municipality'    => 'Cartilla Informativa: Municipalidad',
        'credential'                           => 'Credencial: Fecha Expedición',
        'credential_expiration_date'           => 'Credencial: Fecha Vencimiento',
        'credential_municipality'              => 'Credencial: Municipalidad',
        'score'                                => 'Puntos Acumulados',
        'details'                              => 'Detalles',
    ],
    'Propietarios' => [
        'name'                     => 'Empresa/Nombre',
        'document_type'            => 'Tipo de documento',
        'document_number'          => 'Número de documento',
        'document_expiration_date' => 'Doc F.Vencimiento',
        'birthdate'                => 'Fecha Nacimiento',
        'address'                  => 'Dirección',
        'district'                 => 'Distrito',
        'phone'                    => 'Teléfono',
        'email'                    => 'Email',
        'status'                   => 'Estado',
    ],
    'Salidas' => [
        'departure_date' => 'Fecha de salida',
        'vehicle_id'     => 'Vehículo',
        'driver_id'      => 'Conductor',
        'passengers'     => 'Pasajeros',
        'passage'        => 'Pasaje',
        'total'          => 'Total',
        'observations'   => 'Observaciones',
        'user_id'        => 'Usuario',
        'headquarter_id' => 'Sede',
    ],
    'Pagos' => [
        'date'           => 'Fecha',
        'vehicle_id'     => 'Vehículo',
        'driver_id'      => 'Conductor',
        'amount'         => 'Monto',
        'type'           => 'Tipo',
        'detail'         => 'Detalle',
        'user_id'        => 'Usuario',
        'headquarter_id' => 'Sede',
    ],
    'Ingresos' => [
        'date'    => 'Fecha',
        'reason'  => 'A',
        'detail'  => 'Motivo',
        'total'   => 'Monto',
        'currency'=> 'Moneda',
        'user_id' => 'Usuario',
    ],
    'Egresos' => [
        'date'           => 'Fecha',
        'concept_id'     => 'Concepto',
        'kind'           => 'Tipo de egreso',
        'reason'         => 'A',
        'detail'         => 'Motivo / Detalle',
        'amount'         => 'Monto (S/)',
        'voucher_type'   => 'T. Comprobante',
        'user_id'        => 'Responsable',
        'headquarter_id' => 'Sede',
    ],
    'Sucursales' => [
        'name'       => 'Nombre',
        'sort_order' => 'Orden',
        'address'    => 'Dirección',
        'phone'      => 'Teléfono',
        'status'     => 'Estado',
    ],
    'Usuarios' => [
        'name'             => 'Nombre',
        'username'         => 'Usuario',
        'email'            => 'Email',
        'password'         => 'Contraseña',
        'document_type'    => 'Tipo Documento',
        'document_number'  => 'N° Documento',
        'phone'            => 'Teléfono',
        'headquarter_id'   => 'Sede',
        'sort_order'       => 'Orden',
        'status'           => 'Estado',
    ],
    'Conceptos' => [
        'name'       => 'Nombre',
        'sort_order' => 'Orden',
        'kind'       => 'Tipo',
        'status'     => 'Estado',
    ],
];
